# Generated by Django 4.2.5 on 2023-09-19 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_email', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayEventType',
            fields=[
                ('eventtype_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='event_email.eventtype')),
            ],
            bases=('event_email.eventtype',),
        ),
    ]
